#:schema node_modules/wrangler/config-schema.json
name = "kuberha-ai"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[dev]
ip = "0.0.0.0"
port = 5173
local_protocol = "http"
